server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: cloud-gateway-gateway9527 #实例ID
    prefer-ip-address: true #访问显示主机IP地址

spring:
  application:
    name: cloud-gateway-gateway
  cloud:   #配置路由信息--匹配的工程是cloud-provider-hystrix-payment8001
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由功能
      routes:
        - id: payment_routh      # 路由的ID，没有固定规则但要求唯一
          #uri: http://localhost:8001    #匹配后提供服务的路由地址--静态
          uri: lb://CLOUD-PAYMENT-SERVICE  # 动态路由：lb:// 协议表示启动gateway的负载均衡功能
          predicates:
            - Path=/payment/hystrix/ok/get/**       # 断言，路径相匹配的路由地址
        - id: payment_routh2      # 路由的ID，没有固定规则但要求唯一
          #uri: http://localhost:8001            #陪陪后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   # 动态路由：lb:// 协议表示启动gateway的负载均衡功能
          predicates:
            - Path=/payment/hystrix/circuitbreaker/get/**       # 断言，路径相匹配的路由地址


