
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.92.144.90:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123abcABC!
  profiles:
    active: 8001


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.fqh.cloud.payment.entities    # 所有Entity别名类所在包

eureka:
  client:
    #表示十分将自己注册进EurekaServer，默认为true，单机版eureka设置为false
    register-with-eureka: true
    #表示十分从EurekaServer抓取已有的注册信息，默认为true，如果是集群设置，必须设置为true，单点无所谓
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
  instance:
    #显示主机IP
    prefer-ip-address: true
    # Eureka客户端向服务器发送心跳的时间间隔，单位为秒，默认30
    lease-renewal-interval-in-seconds: 30
    # Eureka服务端在收到最后一次心跳后等等时间上线，单位为秒，默认90，超时后eureka Server会剔除服务
    lease-expiration-duration-in-seconds: 90

---
server:
  port: 8001
spring:
  profiles: 8001
eureka:
  instance:
    instance-id: payment8001
---
server:
  port: 8002
spring:
  profiles: 8002
eureka:
  instance:
    instance-id: payment8002