

eureka:
  client:
    #表示十分将自己注册进EurekaServer，默认为true，单机版eureka设置为false
    register-with-eureka: true
    #表示十分从EurekaServer抓取已有的注册信息，默认为true，如果是集群设置，必须设置为true，单点无所谓
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
  instance:
    #显示主机IP
    prefer-ip-address: true
    # Eureka客户端向服务器发送心跳的时间间隔，单位为秒，默认30
    lease-renewal-interval-in-seconds: 30
    # Eureka服务端在收到最后一次心跳后等等时间上线，单位为秒，默认90，超时后eureka Server会剔除服务
    lease-expiration-duration-in-seconds: 90

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称-标识是消息的接受者
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
  profiles:
    active: 8802

---
server:
  port: 8802
eureka:
  instance:
    instance-id: cloud-stream-consumer8802
spring:
  profiles: 8802
  cloud:
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称-标识是消息的接受者
          group: streamGroupA

---
server:
  port: 8803
eureka:
  instance:
    instance-id: cloud-stream-consumer8803
spring:
  profiles: 8803
  cloud:
    bindings: # 服务的整合处理
      input: # 这个名字是一个通道的名称-标识是消息的接受者
        group: streamGroupA