#默认7001
spring:
  profiles:
    active: 7001
---
server:
  port: 7001
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:7002/eureka/
  server:
    enable-self-preservation: false  #关闭自我保护
    eviction-interval-timer-in-ms: 10000 #服务剔除时间为10秒--默认90秒
---
server:
  port: 7002
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/
  server:
    enable-self-preservation: false  #关闭自我保护
    eviction-interval-timer-in-ms: 10000 #服务剔除时间为10秒--默认90秒