server:
  port: 9001

spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#暴露监控断点
management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-payment-service: http://nacos-payment-provider
